---
- name: Delete container and image
    tags: ["run", "wipe"]
    block:
      - name: Stop a container
        docker_container:
          name: mydevopslab
          state: stopped
      - name: remove container
        docker_container:
          name: mydevopslab
          state: absent
      - name: Remove image
        docker_image:
          state: absent
          name: sh1co/devopslab