apiVersion: v1
kind: Service
metadata:
  name: devops-lab
  labels:
    app: devops-lab
spec:
  selector:
    app: devops-lab
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000