name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.7.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .\app_python\requirements-dev.txt -r .\app_python\requirements.txt
      - name: Lint with black
        run: |
          black --check .
      - name: Test with pytest
        run: |
          pytest .\app_python\run_tests.py